graph: don't try to process more root nodes if context is done
hashicorp/go-eventlogger pull request #114
Opened 2024-07-25 14:42 UTC by peteski22

`graph.process` While ranging over the root nodes, do not invoke any more roots when we know the context is already `Done`

2024-08-09 14:11 UTC, jimlambrt requested changes

2024-08-09 14:11 UTC, jimlambrt commented on graph.go
> +			select {
test?

2024-08-11 20:04 UTC, peteski22 commented on graph.go
> +			select {
https://github.com/hashicorp/go-eventlogger/pull/114/commits/87603cccb964d950ed63a06095fac51b32073e8a

2024-08-12 13:53 UTC, jimlambrt approved these changes

2024-08-12 14:08 UTC, merged