Events: filter map fields which are not tagged.
hashicorp/go-eventlogger pull request #63
Opened 2021-09-03 17:03 UTC by jimlambrt

Currently, map fields are only filtered if a `Taggable` interface is implemented which includes the map. This is efficient, but could result in an inadvertent leak of sensitive and/or secret data. This PR changes that behavior by tracking all maps which are encountered while processing the event and before returning, it filters all the remaining unfiltered maps fields.

2021-09-13 16:21 UTC, tmessi requested changes
Can you update the [README](https://github.com/hashicorp/go-eventlogger/blob/main/filters/encrypt/README.md) and potentially the [examples](https://github.com/hashicorp/go-eventlogger/blob/main/filters/encrypt/docs_test.go) to show how this behaves? The way the structs are created in the tests make it difficult to grok the end-to-end behavior. 

So for example, I updated the struct in the `ExampleFilter`:

```go
p := &struct {
    NoClassification string
    Public           string `class:"public"`
    Sensitive        string `class:"sensitive,redact"`
    Secret           string `class:"secret,redact"`
    SecretMap        map[string]string
}{
    NoClassification: "no classification",
    Public:           "public",
    Sensitive:        "sensitive",
    Secret:           "secret",
    SecretMap: map[string]string{
        "foo": "bar",
    },
}
```

Which results in:

```
{"created_at":"2009-11-17T20:34:58.651387237Z","event_type":"test-event","payload":{"NoClassification":"\u003cREDACTED\u003e","Public":"public","Sensitive":"\u003cREDACTED\u003e","Secret":"\u003cREDACTED\u003e","SecretMap":{"foo":"\u003cREDACTED\u003e"}}}
```

Which I think makes sense based on these changes, although it does seem a little confusing compared to the "NoClassification" field.

And if I modify the example to do:

```go
p := &struct {
    NoClassification string
    Public           string            `class:"public"`
    Sensitive        string            `class:"sensitive,redact"`
    Secret           string            `class:"secret,redact"`
    PublicMap        map[string]string `class:"public"`
}{
    NoClassification: "no classification",
    Public:           "public",
    Sensitive:        "sensitive",
    Secret:           "secret",
    PublicMap: map[string]string{
        "foo": "bar",
    },
}
```
It does:
```
{"created_at":"2009-11-17T20:34:58.651387237Z","event_type":"test-event","payload":{"NoClassification":"\u003cREDACTED\u003e","Public":"public","Sensitive":"\u003cREDACTED\u003e","Secret":"\u003cREDACTED\u003e","PublicMap":{"foo":"\u003cREDACTED\u003e"}}}
```
Which is not what I would expect, but perhaps I am just not familiar enough with this library? But in that case some additional docs would help others like me :)

2021-09-14 15:06 UTC, jimlambrt commented
@tmessi Thanks for the feedback.  I'll update the docs.  The behavior is expected, given the change you made.  The pkg doesn't support/honor the `class` tag on a map.  Instead, you need to implement the `Taggable` interface, which specifies tags for the keys of a map.  Does that make sense?

2021-09-14 15:28 UTC, tmessi commented
> The pkg doesn't support/honor the `class` tag on a map. Instead, you need to implement the `Taggable` interface, which specifies tags for the keys of a map. Does that make sense?

Yea, that makes sense. Its just that now you need to implement `Taggable` if you *do* want to expose values in the map, which is a change to how the docs are currently worded.

2021-09-14 16:30 UTC, tmessi approved these changes
ty for the doc updates!

2021-09-14 17:33 UTC, louisruch approved these changes
This looks great

2021-09-14 18:13 UTC, merged